[package]
name = "zelana-execution"
version = "0.1.0"
edition = "2021"

[dependencies]
zelana-core = { workspace = true }
wincode = {workspace = true}
anyhow = { workspace = true }
thiserror = { workspace = true }
blake3 ={workspace = true}