[package]
name = "sp1-prover"
version = "0.1.0"
edition = "2021"

[dependencies]
sp1-zkvm = "5.2.3"
zelana-core = { workspace = true }
zelana-execution = { workspace = true }
wincode = { workspace = true}
blake3 = { workspace = true }
anyhow = {workspace = true}